sudo: true
cache: pip

language: python
python: '3.7'
dist: xenial

stages:
  - lint
  - docs
  - test

jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=flake8
    - env: TOXENV=pyroma
    # docs stage
    - stage: docs
      env: TOXENV=readme
    # test stage
    - stage: test
      env: TOXENV=py

matrix:
  allow_failures:
    - env: TOXENV=xenon
    - env: TOXENV=mypy

install:
  - sh -c 'if [ "$TOXENV" = "py" ]; then pip install tox codecov; else pip install tox; fi'

script:
  - tox

after_success:
  - sh -c 'if [ "$TOXENV" = "py" ]; then tox -e coverage-report; codecov; fi'
